modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL=""

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL=""
displayURL=""
logoFile=""
credits="Koyoharu Gotouge for creating Kimetsu no Yaiba"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.demonslayer]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.demonslayer]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
